export const DASHBOARD_URL = "/dashboard"
export const GROUPS_URL = "/groups"
export const INCIDENT_URL = "/incident"
export const TAG_Query = "?tag=true"
export const MANAGER_URL = "/manager"
export const LOGIN = "/login"
export const COUNTERMEASURE = "/countermeasure"

export const RECEIVER_URL = "/receiver"
export const ID_PARAM = "/:id"
export const BASE_URL = "http://localhost:8080"
